---
- name: TP6
  hosts: all
  become:  true
  tasks:
    - name: Sécurisation de la connexion ssh de l'utilisateur ansible depuis uniquement l'utilisateur ansible venant de SRV-Ansible et neutralisation de la connexion ssh par mdp sur cet utilisateur.
      blockinfile:
        path: /etc/ssh/sshd_config
        append_newline: true
        prepend_newline: true
        block: |
          Match User ansible
          AllowUsers ansible@192.168.64.128
          PasswordAuthentication no
    - name: Neutralisation de la connexion par mot de passe de l'utilsateur ansible.
      user:
        name: ansible
        password: '!'
        password_lock: true
    - name: Installation du service bind.
      dnf:
        name: bind
        state: latest
        update_cache: yes
    - name: Démarrage du service bind.
      service:
        name: named
        state: started
        enabled: yes