name: CI Pipeline

permissions:
  contents: read

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Execute le playbook ansible sur le Staging.
        run: ansible-playbook serveur_dns.yml

      - name: Execute le playbook ansible sur la Prod.
        run: ansible-playbook -i inventory/prod serveurs_dns.yml
